export { default as LoginImg } from "./Login.svg"
export { default as WorkerImg } from "./Worker.png"
export { default as ClientImg } from "./Client.png"
export { default as LandingImg } from "./Landing.png"
export { default as Procedure1Img } from "./Procedure1.jpg"